services:
  modelgen:
    image: ghcr.io/edencehealth/sqlalchemy-omopcdm-modelgen:1
    environment:
      DB_HOST: cdmdb
      DB_USER: ${TARGET_DB_USER}
      DB_PASSWORD: ${TARGET_DB_PASSWORD}
      DB_NAME: ${TARGET_DB_NAME}
      OUTPUT_FILE: "/output/omopcdm54.py"
      OPTIONS: "nobidi"
      GENERATOR: "declarative"
    depends_on:
      cdmdb:
        condition: service_healthy
    restart: no
    volumes:
      - "./src/sqlalchemy_omopcdm:/output:rw"

  # https://hub.docker.com/_/postgres
  cdmdb:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${TARGET_DB_USER}
      POSTGRES_PASSWORD: ${TARGET_DB_PASSWORD}
      POSTGRES_DB: ${TARGET_DB_NAME}
      PGDATA: "/pgdata"
      # the following values are libpq envvars which make it easier to exec psql
      # and the other tools
      PGDATABASE: ${TARGET_DB_NAME}
      PGUSER: ${TARGET_DB_USER}
      PGPASSWORD: ${TARGET_DB_PASSWORD}
    volumes:
      - "targetdb:/pgdata:rw"
    healthcheck:
      interval: 10s
      retries: 10
      test:
        - CMD
        - /usr/local/bin/pg_isready
      timeout: 3s
    command:
      - -c
      - shared_buffers=256MB
      - -c
      - max_connections=200
    restart: unless-stopped
    shm_size: 2gb

volumes:
  targetdb:
